Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "prepared-box"
    db.ssh.username = "root"
  end

  config.vm.define "web" do |web|
    web.vm.box = "prepared-box"
    web.ssh.username = "root"
  end
end