name: Wheel
on:
  push:
  pull_request:

env:
  UV_PYTHON_PREFERENCE: only-system
  UV_NO_SYNC: 1

jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: "3.14"
          architecture: x64

      - name: Install uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          enable-cache: true

      - name: Build wheel
        run: uv build